export const USER_REPOSITORY = 'USER_REPOSITORY';
export const BANK_ACCOUNT_HISTORY_REPOSITORY =
  'BANK_ACCOUNT_HISTORY_REPOSITORY';
export const BANK_ACCOUNT_REPOSITORY = 'BANK_ACCOUNT_REPOSITORY';
